# Generated by Django 6.0.6 on 2026-06-07 18:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('grid_columns', models.PositiveIntegerField(default=32)),
                ('max_width_px', models.PositiveIntegerField(default=1400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BaseWidget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('widget_type', models.CharField(max_length=50)),
                ('subtype', models.CharField(blank=True, max_length=50, null=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('state', models.JSONField(blank=True, default=dict)),
                ('row', models.PositiveIntegerField(default=1)),
                ('column', models.PositiveIntegerField(default=1)),
                ('width_units', models.PositiveIntegerField(default=1)),
                ('height_units', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='dashboard.dashboard')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
