# Generated by Django 6.0.6 on 2026-07-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbench', '0002_kernelsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='cells',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='notebook',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='NotebookCell',
        ),
    ]
